# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=30, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('bvn', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('verifyUsing', models.CharField(blank=True, choices=[('Voice', 'Voice'), ('SMS', 'SMS')], max_length=30, null=True)),
                ('country', models.CharField(blank=True, choices=[('NG', 'Nigeria')], max_length=30, null=True)),
            ],
        ),
    ]
