# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='user_name',
            new_name='name',
        ),
    ]
